Feature/2 translate
WildCodeSchool/remotefr-js-0920-p3-off-hungergames-front pull request #16
Opened 2021-01-20 09:42 UTC by MatisseFMLR

2021-01-20 13:57 UTC, lgiacalo requested changes

2021-01-20 13:57 UTC, lgiacalo commented on src/views/SettingsView.vue
> +          <div>
Il ny aurait pas une div en trop ?

2021-01-20 15:00 UTC, MatisseFMLR commented on src/views/SettingsView.vue
> +          <div>
Si carrement, même deux, je corrige ça !

2021-01-21 22:07 UTC, lgiacalo approved these changes

2021-01-21 22:08 UTC, merged